package com.example.smartmartplus;

import android.content.Intent;
import android.os.Bundle;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.gms.common.moduleinstall.ModuleInstall;
import com.google.android.gms.common.moduleinstall.ModuleInstallRequest;
import com.google.mlkit.vision.barcode.common.Barcode;
import com.google.mlkit.vision.codescanner.GmsBarcodeScanner;
import com.google.mlkit.vision.codescanner.GmsBarcodeScannerOptions;
import com.google.mlkit.vision.codescanner.GmsBarcodeScanning;

public class StoreQRScannerActivity extends AppCompatActivity {

    private GmsBarcodeScanner scanner;

    // TEMPORARY STORE UUID
    private static final String STORE_ID =
            "9cb5a337-f91e-46ec-a968-70776391f6ec";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Google Code Scanner provides its own scanning UI.
        setupScanner();
    }

    private void setupScanner() {

        // QR CODE ONLY
        GmsBarcodeScannerOptions options =
                new GmsBarcodeScannerOptions.Builder()
                        .setBarcodeFormats(
                                Barcode.FORMAT_QR_CODE
                        )
                        .build();

        scanner =
                GmsBarcodeScanning.getClient(
                        this,
                        options
                );

        // Install Google Code Scanner module if necessary
        ModuleInstallRequest request =
                ModuleInstallRequest.newBuilder()
                        .addApi(scanner)
                        .build();

        ModuleInstall.getClient(this)
                .installModules(request)
                .addOnSuccessListener(
                        unused -> startScanning()
                )
                .addOnFailureListener(
                        e -> {

                            Toast.makeText(
                                    StoreQRScannerActivity.this,
                                    "Unable to prepare QR scanner",
                                    Toast.LENGTH_LONG
                            ).show();

                            finish();
                        }
                );
    }

    private void startScanning() {

        scanner.startScan()
                .addOnSuccessListener(
                        barcode -> {

                            String qrValue =
                                    barcode.getRawValue();

                            if (qrValue == null ||
                                    qrValue.trim().isEmpty()) {

                                Toast.makeText(
                                        StoreQRScannerActivity.this,
                                        "Invalid store QR code",
                                        Toast.LENGTH_SHORT
                                ).show();

                                startScanning();
                                return;
                            }

                            verifyStoreQR(qrValue);
                        }
                )
                .addOnCanceledListener(
                        () -> {

                            Toast.makeText(
                                    StoreQRScannerActivity.this,
                                    "QR scanning cancelled",
                                    Toast.LENGTH_SHORT
                            ).show();

                            finish();
                        }
                )
                .addOnFailureListener(
                        e -> {

                            Toast.makeText(
                                    StoreQRScannerActivity.this,
                                    "QR scan failed",
                                    Toast.LENGTH_LONG
                            ).show();

                            finish();
                        }
                );
    }

    private void verifyStoreQR(String qrValue) {

        /*
         * TEMPORARY FRONTEND TEST
         *
         * For now we don't need a real store QR
         * generated by Supabase.
         *
         * Any QR containing this UUID will be accepted.
         */

        if (qrValue.contains(STORE_ID)) {

            // SAVE STORE VERIFICATION
            getSharedPreferences(
                    "SmartMartPrefs",
                    MODE_PRIVATE
            )
                    .edit()
                    .putBoolean(
                            "STORE_VERIFIED",
                            true
                    )
                    .putString(
                            "STORE_ID",
                            STORE_ID
                    )
                    .putString(
                            "STORE_NAME",
                            "SmartMart+ Main Store"
                    )
                    .putString(
                            "STORE_ADDRESS",
                            "Bangalore, Karnataka"
                    )
                    .apply();

            Toast.makeText(
                    StoreQRScannerActivity.this,
                    "Store verified successfully!",
                    Toast.LENGTH_SHORT
            ).show();

            openHomeAsInsideStore();

        } else {

            Toast.makeText(
                    StoreQRScannerActivity.this,
                    "Invalid SmartMart+ store QR",
                    Toast.LENGTH_LONG
            ).show();

            // Allow the user to try again
            startScanning();
        }
    }

    private void openHomeAsInsideStore() {

        Intent intent =
                new Intent(
                        StoreQRScannerActivity.this,
                        HomeActivity.class
                );

        intent.putExtra(
                "INSIDE_STORE",
                true
        );

        intent.putExtra(
                "STORE_ID",
                STORE_ID
        );

        intent.putExtra(
                "STORE_NAME",
                "SmartMart+ Main Store"
        );

        intent.putExtra(
                "STORE_ADDRESS",
                "Bangalore, Karnataka"
        );

        intent.setFlags(
                Intent.FLAG_ACTIVITY_CLEAR_TOP |
                        Intent.FLAG_ACTIVITY_SINGLE_TOP
        );

        startActivity(intent);

        finish();
    }
}